name: CI

on: 
  push: 
    branches:
    - main
    - Testing
    - Local

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node 20.12.2
        uses: actions/setup-node@v2
        with:
          node-version: 20.12.2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:unit
